# Generated by Django 4.0.4 on 2023-01-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('PPE', 'PPE'), ('Tests', 'Tests'), ('Cleaning', 'Cleaning'), ('Supplies', 'Supplies'), ('Equipment', 'Equipment'), ('Miscallaneous', 'Miscallaneous')], max_length=20, null=True)),
                ('quantity', models.PositiveBigIntegerField(null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
