# Generated by Django 4.0.4 on 2023-01-13 01:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_alter_item_options_alter_order_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Request',
        ),
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
        migrations.RenameField(
            model_name='request',
            old_name='order_quantity',
            new_name='request_quantity',
        ),
    ]
