# Generated by Django 4.0.4 on 2023-01-13 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_order_request_alter_request_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_quantity',
            new_name='order_quantity',
        ),
    ]
