# Generated by Django 4.0.4 on 2023-01-13 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_request_quantity_request_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='order_quantity',
            new_name='quantity',
        ),
    ]
