# Generated by Django 4.0.4 on 2023-01-13 01:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_rename_order_quantity_request_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Requisition',
        ),
    ]
